### ISSUE TITLE
Trouble running out-of-box

### ISSUE THREAD

**Issue by richb-hanover** [PBRT/reactogo#3]
Using node 5.9.1 and npm 3.7.3 on OSX 10.10.5... I tried the naive installation (git clone/npm install/npm run start) Everything seemed to install and startup just fine.

I go to localhost:3000 but get a blank browser window. I've attached the npm command output and the resulting HTML (at the bottom) in this pastebin: http://pastebin.com/ZSpQxdNT

Any thoughts?

**Comment by PBRT** [comment]
Hi,
Everything seems to work fine in your pastebin (installation and build). I just tried with node 5.9.1 with NPM 3.7.3 and it works as well.
Do you have any errors in the browser console? Which browser are you using?
Also do you have something when you go on http://localhost:9000? It's the default port used by the express server and should as well display the app.
You can also try to build the app locally and run node server/server.js. It should display the app as well, let me know if it's working.

**Comment by richb-hanover** [comment]
Ahah! Do you mean this error message? :-) `firebase-web.js:36 Uncaught Error: FIREBASE FATAL ERROR: Cannot parse Firebase url. Please use https://<YOUR FIREBASE>.firebaseio.com` I don't have a Firebase ID, and didn't want to set one up just to see the demo.

I wonder if the demo could work without a firebase configuration, and only give an error message in the GUI when someone clicked Login... Thanks!

**Comment by PBRT** [comment]
Ah, correct that's why! Well spotted!

I forgot to add a condition for using it without firebase (which should be the case, firebase integration is part of the project as a demo).
I just fixed it as part of https://github.com/PBRT/reactogo/pull/4. Now, it's only when you click on Login that a firebase id is required but it won't crash the app. All the rest is still available.

Thanks for the feedback, let me know if it's working for you!

**Comment by richb-hanover** [comment]
Bingo! It works as desired. Thanks!

PS It would be good to add npm-debug.log to the .gitignore file...

**Comment by PBRT** [comment]
Will do! Thanks!
