### ISSUE TITLE
localhost:3000 results in 502 Bad gateway

### ISSUE THREAD

**Issue by gdq** [PBRT/reactogo#6]
Dear,

I installed as outlined, and try to run the sample application:
http://localhost:3000/ gives a 502 Bad Gateway error
http://localhost:9000/ works fine.

Any clue what I might have done wrong?

Thanks and kind regards,

geert

**Comment by PBRT** [comment]
Hi Geert, it's look like there is some issue with the Webpack dev server. 

Are you running `npm run start`? Because this will start the express server on the port 9000 and the WebPack dev serve on the 3000. Could you also try to run `npm run build` and once finish `node server/server.js`? 

Also, another possible issue could be some local DNS configuration maybe? Do you have any redirection on your localhost:3000.

Cheers,

**Comment by PBRT** [comment]
Unable to reproduce
